<?php

/**
 * Implements hook_theme().
 */
function block_example_theme() {
  return [
    'hello_block' => [
      'variables' => [
        'data' => [],
      ],
    ],
  ];
}

function block_example_block_view_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
  \Drupal::service('civicrm')->initialize();
  \CRM_Core_Resources::singleton()->addCoreResources();
  \Civi::service('angularjs.loader')
    ->addModules('afformMyForm');
}
